name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > mykey.pem
          chmod 600 mykey.pem

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          scp -o StrictHostKeyChecking=no -i mykey.pem -r ./dist ${EC2_USER}@${EC2_HOST}:~/hello-world
          ssh -o StrictHostKeyChecking=no -i mykey.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
            cd ~/hello-world
            npm install --production
            pm2 restart hello-world || pm2 start dist/main.js --name "hello-world"
            pm2 save
          EOF
