name: Deploy Next.js App to EC2 (Secure)

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runner environment

    steps:
      - uses: actions/checkout@v3  # Checkout code from GitHub repository

      - name: Install Node.js and npm
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Install PM2
        run: |
          npm install pm2 -g

      - name: SSH into EC2 instance and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}  # Secret containing your private SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@13.201.92.195 << 'EOF'
            cd /src  

            git pull origin main

            npm install

            npm run build

            pm2 stop all  # Stop all running PM2 processes
            pm2 start npm --name "nextjs-app" -- start
            pm2 save
          EOF
