name: Deploy NestJS App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the appropriate version for your app

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Verify build output
        run: ls -la dist

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Create remote directory if not exists
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST "mkdir -p /home/$EC2_USER/nodejs-app-ec2"

          # Copy build files to EC2
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./dist/* $EC2_USER@$EC2_HOST:/home/$EC2_USER/nodejs-app-ec2/

          # Install dependencies and start app with PM2
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/$EC2_USER/nodejs-app-ec2/
            npm install --production

            if ! pm2 list | grep -q nestjs-app; then
              pm2 start dist/main.js --name nestjs-app
            else
              pm2 restart nestjs-app
            fi

            pm2 save
            sudo pm2 startup systemd -u $EC2_USER --hp /home/$EC2_USER
          EOF
